from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginForm(object):
    def setupUi(self, LoginForm):
        LoginForm.setObjectName("LoginForm")
        LoginForm.resize(637, 408)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../img/avater.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        LoginForm.setWindowIcon(icon)
        self.label = QtWidgets.QLabel(LoginForm)
        self.label.setGeometry(QtCore.QRect(210, 20, 200, 121))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../img/xg.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.userNameInput = QtWidgets.QLineEdit(LoginForm)
        self.userNameInput.setGeometry(QtCore.QRect(180, 170, 291, 41))
        self.userNameInput.setStyleSheet("font: 75 10pt \"Consolas\" rgb(241, 255, 235);")
        self.userNameInput.setObjectName("userNameInput")
        self.userPasswordInput = QtWidgets.QLineEdit(LoginForm)
        self.userPasswordInput.setGeometry(QtCore.QRect(180, 250, 291, 41))
        self.userPasswordInput.setStyleSheet("font: 75 10pt \"Consolas\" rgb(241, 255, 235);")
        self.userPasswordInput.setObjectName("userPasswordInput")
        self.signInButton = QtWidgets.QPushButton(LoginForm)
        self.signInButton.setGeometry(QtCore.QRect(260, 330, 112, 34))
        self.signInButton.setStyleSheet("font: 75 10pt \"Consolas\"rgb(241, 255, 235);\n""")
        self.signInButton.setObjectName("signInButton")
        self.signUpButton = QtWidgets.QPushButton(LoginForm)
        self.signUpButton.setGeometry(QtCore.QRect(510, 365, 112, 34))
        self.signUpButton.setStyleSheet("font: 75 10pt \"Consolas\"rgb(241, 255, 235);")
        self.signUpButton.setObjectName("signUpButton")
        self.userNameLable = QtWidgets.QLabel(LoginForm)
        self.userNameLable.setGeometry(QtCore.QRect(90, 170, 91, 31))
        self.userNameLable.setStyleSheet("font: 75 10pt \"Consolas\"rgb(241, 255, 235); font: bold")
        self.userNameLable.setObjectName("userNameLable")
        self.userPasswordLable = QtWidgets.QLabel(LoginForm)
        self.userPasswordLable.setGeometry(QtCore.QRect(70, 250, 91, 31))
        self.userPasswordLable.setStyleSheet("font: 75 10pt \"Consolas\"rgb(241, 255, 235); font: bold")
        self.userPasswordLable.setObjectName("userPasswordLable")
        self.userNameTipsLabel = QtWidgets.QLabel(LoginForm)
        self.userNameTipsLabel.setGeometry(QtCore.QRect(180, 220, 231, 21))
        self.userNameTipsLabel.setStyleSheet("font: 9pt \"Consolas\" rgb(255, 14, 30);")
        self.userNameTipsLabel.setObjectName("userNameTipsLabel")
        self.userPasswordTipsLabel = QtWidgets.QLabel(LoginForm)
        self.userPasswordTipsLabel.setGeometry(QtCore.QRect(180, 300, 231, 21))
        self.userPasswordTipsLabel.setStyleSheet("font: 9pt \"Consolas\" rgb(255, 14, 30);")
        self.userPasswordTipsLabel.setObjectName("userPasswordTipsLabel")

        self.retranslateUi(LoginForm)
        QtCore.QMetaObject.connectSlotsByName(LoginForm)

    def retranslateUi(self, LoginForm):
        _translate = QtCore.QCoreApplication.translate
        LoginForm.setWindowTitle(_translate("LoginForm", "欢迎登陆航味食堂"))
        self.signInButton.setText(_translate("LoginForm", "登陆"))
        self.signUpButton.setText(_translate("LoginForm", "注册"))
        self.userNameLable.setText(_translate("LoginForm", "用户名："))
        self.userPasswordLable.setText(_translate("LoginForm", "用户密码："))
        self.userNameTipsLabel.setText(_translate("LoginForm", "该用户名不存在!"))
        self.userPasswordTipsLabel.setText(_translate("LoginForm", "密码错误!"))