from PyQt5 import QtCore, QtGui, QtWidgets


class Suggest_window(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1139, 716)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(30, 100, 600, 460))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.dish_label = QtWidgets.QLabel(self.centralwidget)
        self.dish_label.setGeometry(QtCore.QRect(80, 20, 501, 71))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.dish_label.setStyleSheet("font:13pt")
        self.dish_label.setObjectName("dish_label")
        self.nutrition_label = QtWidgets.QLabel(self.centralwidget)
        self.nutrition_label.setGeometry(QtCore.QRect(720, 20, 281, 71))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.nutrition_label.setStyleSheet("font:13pt")
        self.nutrition_label.setObjectName("nutrition_label")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(670, 100, 405, 181))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.conclu_label = QtWidgets.QLabel(self.centralwidget)
        self.conclu_label.setGeometry(QtCore.QRect(260, 560, 781, 81))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.conclu_label.setStyleSheet("font:13pt")
        self.conclu_label.setWordWrap(True)
        self.conclu_label.setObjectName("conclu_label")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(670, 340, 405, 220))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.taste_label = QtWidgets.QLabel(self.centralwidget)
        self.taste_label.setGeometry(QtCore.QRect(780, 280, 131, 71))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.taste_label.setStyleSheet("font:13pt")
        self.taste_label.setObjectName("taste_label")
        self.suggest_label = QtWidgets.QLabel(self.centralwidget)
        self.suggest_label.setGeometry(QtCore.QRect(240, 615, 651, 61))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        self.suggest_label.setStyleSheet("font:11pt")
        self.suggest_label.setObjectName("suggest_label")
        self.backButton = QtWidgets.QPushButton(self.centralwidget)
        self.backButton.setGeometry(QtCore.QRect(1030, 650, 93, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.backButton.setStyleSheet("font:12pt")
        self.backButton.setObjectName("backButton")
        self.reComeButton = QtWidgets.QPushButton(self.centralwidget)
        self.reComeButton.setGeometry(QtCore.QRect(920, 650, 93, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.reComeButton.setStyleSheet("font:8pt")
        self.reComeButton.setObjectName("reComeButton")

        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.dish_label.setText(_translate("MainWindow", "以下是您吃过的菜品里频次最高的五款菜品："))
        self.nutrition_label.setText(_translate("MainWindow", "目前营养物质摄入情况："))
        self.conclu_label.setText(_translate("MainWindow", "考虑到您的口味偏好与营养摄入状况,我们为您推荐以下菜品:"))
        self.taste_label.setText(_translate("MainWindow", "口味偏好："))
        self.suggest_label.setText(_translate("MainWindow", "TextLabel"))
        self.backButton.setText(_translate("MainWindow", "返回"))
        self.reComeButton.setText(_translate("MainWindow", "再来一组"))
